# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build:
    docker:
      - image: charlesnicholson/circleci-images:latest
    steps:
      - checkout
      - run: ./b

workflows:
  submit-gate:
    jobs:
      - build
